### ISSUE TITLE
No module named 'eq_dataset'

### ISSUE THREAD

**Issue by jatan12** [cloneofsimo/poly2SOP#1]
Hi there, 

I was trying to run the code that you provided but it seems to be missing one of the modules. Could you share the missing file and also the pretrained model?

**Comment by cloneofsimo** [comment]
Sure. Currently I am busy preparing midterm exam, so I will notify you right after end of the exam.

**Comment by jatan12** [comment]
That'd be great

**Comment by troy1729** [comment]
Hi there,

A follow up on the same if you can share the eq_dataset file!

**Comment by cloneofsimo** [comment]
@troy1729 @jatan12 I added it!
